# docker-compose.yml
version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - bootstrap.memory_lock=true
    ports:
      - "9200:9200"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -u $ELASTIC_USER:$ELASTIC_PASSWORD -f http://localhost:9200/_cluster/health"]
      interval: 10s
      retries: 10
      timeout: 15s
    command: >
      bash -c "
        if [ ! -d /usr/share/elasticsearch/plugins/analysis-nori ]; then
          elasticsearch-plugin install analysis-nori --batch;
        fi &&
        /usr/local/bin/docker-entrypoint.sh elasticsearch
      "

  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.2
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=${KIBANA_USER}
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}

  fastapi:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: fastapi-app
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      elasticsearch:
        condition: service_healthy
    env_file:
      - ./.env
    volumes:
      - ./gemini_config.json:/gemini_config.json:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/gemini_config.json

volumes:
  elastic_data:
